version: '3.6'
services:

  app:
    depends_on:
      - maria
      - bitcoin
      - liquid
      - lnd
    container_name: app
    image: coinos-server-staging:0.0.1
    ports:
      - '3118:3118'
      - '3119:3119'
    environment:
      NODE_ENV: development
    volumes:
      - ./config:/app/config
    command: node index
    
  ui:
    profiles:
       - donotstart

  clightning:
    profiles:
       - donotstart

  #static serving:  
  nginx: 
    depends_on:
    - app
    image: nginx:1.20.2
    container_name: nginx
    volumes:
      - type: bind 
        source: ./config/nginx/default.conf
        target: /etc/nginx/conf.d/default.conf
      - ../coinos-ui/dist:/coinos      

  #automatic SSL: 
  nginx-ssl-proxy:
    depends_on:
    - nginx
    container_name: nginx-ssl-proxy
    image: danieldent/nginx-ssl-proxy
    environment:
      UPSTREAM: 'nginx:80' #< send traffic to nginx service above
      SERVERNAME: ${HOST}
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./config/letsencrypt:/etc/letsencrypt
      
networks: 
  default: 
    external: 
      name: net      