version: '3.6'
services:

  ui:
    profiles:
       - donotstart

  nginx: 
    depends_on:
    - app
    image: nginx:1.20.2
    container_name: nginx
    volumes:
      - type: bind 
        source: ./config/nginx/default.conf
        target: /etc/nginx/conf.d/default.conf
      - ../coinos-ui/dist:/coinos
    ports:
      - 80:80

networks: 
  default: 
    external: 
      name: net      