version: '3.6'
services:

  app:
    depends_on:
      - maria
      - bitcoin
      - liquid
      - lnd
    container_name: app
    image: coinos-server-staging:0.0.1
    ports:
      - '3118:3118'
      - '3119:3119'
    environment:
      NODE_ENV: development
    volumes:
      - ./:/app

  ui:
    profiles:
       - donotstart

  nginx: 
    depends_on:
    - app
    image: nginx:1.20.2
    container_name: nginx
    volumes:
      - type: bind 
        source: ./config/nginx/default.conf
        target: /etc/nginx/conf.d/default.conf
      - ../coinos-ui/dist:/coinos
    ports:
      - 80:80

networks: 
  default: 
    external: 
      name: net      