export default {
  addresses: {},
  challenge: {},
  change: [],
  issuances: {},
  logins: {},
  nodes: [],
  seen: [],
  sessions: {},
  sockets: {},
  unaccounted: [],
  networks: [],
  rates: { USD: 20000 },
  fx: {},
  assets: {},
  bcAddressIndex: 0,
  lqAddressIndex: 0,
  last: {},
  payments: [],
  fetching: {},
  timeouts: {},
};
